/**
 * NamoIndia
 */
/**
 * This file contains the application's colors.
 *
 * Define color here instead of duplicating them throughout the components.
 * That allows to change them more easily later on.
 */

export default COLOR_CONST = {
    darkishBlue: '#004491',
    pastelRed: '#e65e52',
    defaultBgColor: '#f2f2f2',
    charcoalGrey: '#3e454f',
    darkGreyBlue: '#31414f',
    greenButton: '#29af9d',
    greenBlue:'#43b7a7',
    borderduckEggBlue: '#eaf0fb',
    paleGrey: '#f6f8fa',
    paleGreyTwo: '#eef2f6',
    paleGreyThree: '#f4f5f6',
    paleGreyFour: '#eff2f5',
    modalTransparentBg: 'rgba(0,0,0, 0.2)',
    LightlightNavy: '#195aa4',
    boderdarkishBlueTwo: '#054995',
    lightBlueGrey: '#d8e2ea',
    uploadBG: '#f3f4f4',
    coolGrey:'#8c9096',
    darkishBlueTwo:'#054995',
    coolGreyTwo :"#8b8f95",
    whiteTwo:"#f9f9f9",
    darkBlueGrey: "#101c2f",
    white: '#ffffff',
    lightWhite: '#fafeff',
    buttonColor: '#8ca9b9',
    darkTitle: '#202326',
    appBgColor: '#f5f5f7',
    lightGreyText: '#d8d8d8',
    redAlertColor: '#ff0000',
    darkGreyText: '#616266',
    inActiveDotLightGrey: '#d6d7dc',
    tickColor: '#8ca9b9',
    black: '#000000',
    bellLightGrey: '#f1f3f6',
    readCellBgColor: '#f9fbfd',
    savedCardsGrey: '#9da8ba',
    transparent: 'rgba(0,0,0,0)',
    text: '#212529',
    primary: '#007bff',
    success: '#28a745',
    error: '#dc3545',
    greenyBlue: '#43b7a8',
    thankYouGrey: '#788aa7',
    dollarValue: '#213052',
    whiteThree:'#dbdbdb',
    darkGrey:'#1e1f21',
    lightNotificationColor: '#d8e4f0',
    newNotificationColor: '#becfe0',

    //*> Namo India Colors:
    greenTheme: '#61CE0B',
    greyColor: '#A6BCD0',
    redLabelColor: '#FF5B56',
    lightPink: '#FFE2E4',
    darkTitleColor: '#304661',
    greyTitleColor: '#748A9D',
    redTextColor: '#FF5B56',
    lightGreenColor: '#DEFFE3',
    lightBackgroundColor: '#E5E5E5',
    lightGreyShade: '#F4F4F4',
    lightGreenNotif: '#e2f2da'
};

export const FONTS = {
    GTWalsheimProBold: 'GTWalsheimPro-Bold',
    GTWalsheimProLight: 'GTWalsheimPro-Light',
    GTWalsheimProMedium: 'GTWalsheimPro-Medium',
    GTWalsheimProRegular: 'GTWalsheimPro-Regular',
    CorbelRegular: 'Corbel',
    CorbelRegularItalic: 'Corbel-Italic',
    CorbelBold: 'Corbel-Bold',
    CorbelBoldItalic: 'Corbel-BoldItalic',
    FuturaLight: 'FuturaBT-Light',
    FuturaLightItalic: 'FuturaBT-LightItalic',
    FuturaMedium: 'FuturaBT-Medium',
    FuturaMediumItalic: 'FuturaBT-MediumItalic',
    FuturaRegular: 'FuturaBT-Book',
    FuturaRegularItalic: 'FuturaBT-BookItalic',
    SegoeRegular: 'SegoeUI',
    SegoeSemibold: 'SegoeUI-Semibold',
    SegoeSemiboldItalic: 'SegoeUI-SemiboldItalic',
    SegoeBold: 'SegoeUI-Bold',
    SegoeBoldItalic: 'SegoeUI-BoldItalic',
    SegoeLight: 'SegoeUI-Light',
    BalooRegular: 'Baloo2-Regular',
    BalooMedium: 'Baloo2-Medium',
    BalooBold: 'Baloo2-Bold',
}